name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out github repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: true
      - name: start postgresql server
        run: |
          sudo systemctl start postgresql.service
          sudo systemctl status postgresql.service
          pg_isready
          psql --version || true
          sudo -u postgres psql -c "ALTER USER ${{secrets.POSTGRES_USER}} PASSWORD '${{secrets.POSTGRES_PASSWORD}}';"
      - name: compile document
        run: |
          docker run --network host --rm \
            -e "BIBINPUTS" \
            -e "BSTINPUTS" \
            -e "MFINPUTS" \
            -e "TEXINPUTS" \
            -e "TFMFONTS" \
            -e "HOME" \
            -e "GITHUB_JOB" \
            -e "GITHUB_REF" \
            -e "GITHUB_SHA" \
            -e "GITHUB_REPOSITORY" \
            -e "GITHUB_REPOSITORY_OWNER" \
            -e "GITHUB_REPOSITORY_OWNER_ID" \
            -e "GITHUB_RUN_ID" \
            -e "GITHUB_RUN_NUMBER" \
            -e "GITHUB_RETENTION_DAYS" \
            -e "GITHUB_RUN_ATTEMPT" \
            -e "GITHUB_REPOSITORY_ID" \
            -e "GITHUB_ACTOR_ID" \
            -e "GITHUB_ACTOR" \
            -e "GITHUB_TRIGGERING_ACTOR" \
            -e "GITHUB_WORKFLOW" \
            -e "GITHUB_HEAD_REF" \
            -e "GITHUB_BASE_REF" \
            -e "GITHUB_EVENT_NAME" \
            -e "GITHUB_SERVER_URL" \
            -e "GITHUB_API_URL" \
            -e "GITHUB_GRAPHQL_URL" \
            -e "GITHUB_REF_NAME" \
            -e "GITHUB_REF_PROTECTED" \
            -e "GITHUB_REF_TYPE" \
            -e "GITHUB_WORKFLOW_REF" \
            -e "GITHUB_WORKFLOW_SHA" \
            -e "GITHUB_WORKSPACE" \
            -e "GITHUB_ACTION" \
            -e "GITHUB_EVENT_PATH" \
            -e "GITHUB_ACTION_REPOSITORY" \
            -e "GITHUB_ACTION_REF" \
            -e "GITHUB_PATH" \
            -e "GITHUB_ENV" \
            -e "GITHUB_STEP_SUMMARY" \
            -e "GITHUB_STATE" \
            -e "GITHUB_OUTPUT" \
            -e "RUNNER_OS" \
            -e "RUNNER_ARCH" \
            -e "RUNNER_NAME" \
            -e "RUNNER_ENVIRONMENT" \
            -e "RUNNER_TOOL_CACHE" \
            -e "RUNNER_TEMP" \
            -e "RUNNER_WORKSPACE" \
            -e "ACTIONS_RUNTIME_URL" \
            -e "ACTIONS_RUNTIME_TOKEN" \
            -e "ACTIONS_CACHE_URL" \
            -e GITHUB_ACTIONS=true \
            -e CI=true \
            -e "POSTGRES_USER=${{secrets.POSTGRES_USER}}" \
            -e "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" \
            -e "POSTGRES_HOST=${{secrets.POSTGRES_HOST}}" \
            -e "POSTGRES_PORT=${{secrets.POSTGRES_PORT}}" \
            -v "/var/run/docker.sock":"/var/run/docker.sock" \
            -v "$HOME:$HOME" \
            -v "$GITHUB_PATH:$GITHUB_PATH" \
            -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" \
            -w "$GITHUB_WORKSPACE" \            
            "ghcr.io/xu-cheng/texlive-full:latest" \
            /bin/bash -eo pipefail -c -- \
              "apk add cargo gcc linux-headers musl-dev postgresql16-client py3-pip python3 python3-dev rust && ./make.sh"                

# deploy to github pages
      - name: deploy book and website
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2
        with:
          branch: gh-pages
          folder: /home/runner/work/databases/databases/website/
          single-commit: true
